- hosts: localhost
  connection: local
  become: true
  
  tasks:
   - name: yum install wget
     yum:
      name: wget
      state: present
   - name: yum install curl
     yum:
      name: curl
      state: present  
#   - name: yum install opel-release
#     yum:
#      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
#      state: present
    - name: dnf install oracle-epel-release-el8
      dnf: 
       name: oracle-epel-release-el8
       state: present
    - name: yum install htop
      yum: 
       name: htop
       state: present
