- hosts: localhost
  connection: local
  become: true
  
  tasks:
   - name: yum install wget
     yum:
      name: wget
      state: present
   - name: yum install curl
     yum:
      name: curl
      state: present  
   - name: yum install oracle-epel-release-el8
     yum: 
      name: oracle-epel-release-el8
      state: present
   - name: copy oracle-epel-repos
     copy: 
       src: files/oracle-epel-ol8.repo
       dest: /etc/yum.repos.d/oracle-epel-ol8.repo
       owner: root
       group: root
       mode: 0660
   - name: yum install htop
     yum: 
      name: htop
      state: present
